#!/usr/bin/env bash

set -e

mkdir -p .browser

browserify -r js-beautify -r ./lib/ajv.js:ajv -o .browser/ajv.beautify.js

find spec -type f -name '*.spec.js' | \
xargs -I {} sh -c \
'export f="{}"; browserify $f -t require-globify -t brfs -x ajv -o $(echo $f | sed -e "s/spec/.browser/");'
