#!/usr/bin/env bash

set -e

echo "About to publish $GITHUB_REF to gh-pages..."

function copyReplace {
  sed "s/](.\/docs\//](.\//g" $1 > $2
}

copyReplace README.md docs/README.md
copyReplace CODE_OF_CONDUCT.md docs/CODE_OF_CONDUCT.md
copyReplace CONTRIBUTING.md docs/CONTRIBUTING.md
copyReplace LICENSE docs/LICENSE.md
