#!/usr/bin/env bash

set -e

if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && $TRAVIS_JOB_NUMBER =~ ".3" ]]; then
  git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '\.md$|^LICENSE$' && {
    rm -rf ../gh-pages
    git clone -b gh-pages --single-branch https://${GITHUB_TOKEN}@github.com/epoberezkin/ajv.git ../gh-pages
    cp *.md ../gh-pages/_source
    cp LICENSE ../gh-pages/_source
    cd ../gh-pages
    ./generate
    git add .
    git commit -am "updated by travis build #$TRAVIS_BUILD_NUMBER"
    git push origin gh-pages
  }
fi
